/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package com.crio.qcalc;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        /*StandardCalculator calc = new StandardCalculator();
        calc.add(1, 2);
        calc.printResult();
        calc.subtract(6, 2);
        calc.printResult();
        calc.multiply(7, 2);
        calc.printResult();
        calc.divide(8, 2);
        calc.printResult();*/
        ScientificCalculator cals = new ScientificCalculator();
        int result = cals.modulo(5, 2);
        System.out.println("modulo= "+result);
       System.out.println(cals.squareOf(3));
        System.out.println(cals.cubeOf(3));
        System.out.println(cals.squareRoot(64));
       
    }
}
    


